CREATE TABLE IF NOT EXISTS public.staging_us_zipcodes (
zip varchar ,
lat varchar ,
lng varchar ,
city varchar ,
state_id varchar ,
state_name varchar ,
zcta varchar ,
parent_zcta varchar ,
population varchar ,
density varchar ,
county_fips varchar ,
county_name varchar ,
county_weights varchar ,
county_names_all varchar ,
county_fips_all varchar ,
imprecise varchar ,
military varchar ,
timezone varchar
);